/* Every phrase the game says, in both languages.
   Hindi here is the Hindi cricket is actually watched in: Devanagari with the
   English terms commentary already uses, not a Sanskritised translation of
   "all-rounder". Player names, franchise names and numerals stay as they are. */

export const STRINGS: Record<string, { en: string; hi: string }> = {
  /* ---------------------------------------------------------------- chrome */
  "app.tagline": { en: "Fan-made IPL draft game", hi: "फ़ैन-मेड IPL ड्राफ़्ट गेम" },
  "nav.howItWorks": { en: "How it works", hi: "कैसे खेलें" },
  "nav.leaderboard": { en: "Leaderboard", hi: "लीडरबोर्ड" },
  "nav.playAFriend": { en: "Play a friend", hi: "दोस्त से खेलें" },
  "nav.board": { en: "Board", hi: "बोर्ड" },
  "nav.backToGame": { en: "Back to the game", hi: "गेम पर वापस" },
  "footer.legal": {
    en: "14–0 is a fan-made game and is not affiliated with the IPL or BCCI. Player names and season ratings are used for description only, and ratings are derived from public season statistics.",
    hi: "14–0 एक फ़ैन-मेड गेम है और इसका IPL या BCCI से कोई संबंध नहीं है। खिलाड़ियों के नाम और सीज़न रेटिंग सिर्फ़ जानकारी के लिए हैं, और रेटिंग सार्वजनिक सीज़न आँकड़ों से निकाली गई हैं।",
  },
  "footer.links": {
    en: "Leaderboard · How ratings work · Contact",
    hi: "लीडरबोर्ड · रेटिंग कैसे बनती है · संपर्क",
  },

  /* ------------------------------------------------------------------ home */
  "home.headline.mobile": {
    en: "Draft an all-time IPL XI. Then try to win every single game.",
    hi: "IPL की ऑल-टाइम XI चुनिए। फिर हर एक मैच जीतकर दिखाइए।",
  },
  "home.headline.desktop": {
    en: "The scoreboard nobody has filled in yet.",
    hi: "वो स्कोरबोर्ड जो आज तक कोई नहीं भर पाया।",
  },
  "home.sub": {
    en: "Spin real IPL squads from 2008 to 2025, take one player from each, and play a full season. Win all fourteen and the board reads 14–0.",
    hi: "2008 से 2025 तक की असली IPL स्क्वाड घुमाइए, हर एक से एक खिलाड़ी चुनिए, और पूरा सीज़न खेलिए। चौदहों जीत लीजिए और बोर्ड पर लिखा होगा 14–0।",
  },
  "home.cta": { en: "Spin your first squad", hi: "पहली स्क्वाड घुमाइए" },
  "home.ctaNote": { en: "About 3 minutes. No sign-up.", hi: "करीब 3 मिनट। कोई साइन-अप नहीं।" },
  "home.bestRuns": { en: "Today's best runs", hi: "आज के सबसे अच्छे रन" },
  "home.seeFullBoard": { en: "See the full board", hi: "पूरा बोर्ड देखें" },
  "home.resetNote": { en: "The board resets at midnight IST.", hi: "बोर्ड आधी रात (IST) पर रीसेट होता है।" },
  "home.daily.title": { en: "Today's challenge", hi: "आज की चुनौती" },
  "home.daily.blurb": {
    en: "Everyone gets the same eleven squads. Compare your XI with the rest of the country.",
    hi: "सबको वही ग्यारह स्क्वाड मिलती हैं। अपनी XI की तुलना पूरे देश से कीजिए।",
  },
  "home.daily.action": { en: "Play", hi: "खेलें" },
  "home.daily.actionLong": { en: "Play today's challenge", hi: "आज की चुनौती खेलें" },
  "home.friend.title": { en: "Play a friend", hi: "दोस्त से खेलें" },
  "home.friend.blurb": {
    en: "You both draft, then one shared league decides it. Send the invite on WhatsApp.",
    hi: "दोनों अपनी-अपनी टीम चुनते हैं, फिर एक ही लीग फ़ैसला करती है। न्योता WhatsApp पर भेजिए।",
  },
  "home.friend.action": { en: "Invite", hi: "बुलाएँ" },
  "home.friend.actionLong": { en: "Create a room", hi: "रूम बनाएँ" },
  "home.steps.title": { en: "How a run works", hi: "एक रन कैसे चलता है" },
  "home.step1.title": { en: "Spin a squad", hi: "स्क्वाड घुमाइए" },
  "home.step1.body": {
    en: "The board lands on a real team-season, like Mumbai Indians 2019 or Deccan Chargers 2009. There are 156 of them, every season from 2008 to 2025.",
    hi: "बोर्ड किसी असली टीम-सीज़न पर रुकता है, जैसे Mumbai Indians 2019 या Deccan Chargers 2009। ऐसी 156 स्क्वाड हैं, 2008 से 2025 तक हर सीज़न की।",
  },
  "home.step2.title": { en: "Pick one player", hi: "एक खिलाड़ी चुनिए" },
  "home.step2.body": {
    en: "From that exact season's squad, and only that one. Eleven spins, two re-spins, four overseas players at most. Legend mode hides the ratings.",
    hi: "उसी सीज़न की स्क्वाड में से, और सिर्फ़ उसी में से। ग्यारह स्पिन, दो री-स्पिन, ज़्यादा से ज़्यादा चार विदेशी खिलाड़ी। लेजेंड मोड में रेटिंग छिपी रहती है।",
  },
  "home.step3.title": { en: "Play the season", hi: "सीज़न खेलिए" },
  "home.step3.body": {
    en: "Fourteen league games, then the playoffs, with the final played ball by ball. Top four go through. Every result reproduces from its seed.",
    hi: "चौदह लीग मैच, फिर प्लेऑफ़, और फ़ाइनल गेंद-दर-गेंद। ऊपर की चार टीमें आगे जाती हैं। हर नतीजा उसी सीड से दोबारा निकाला जा सकता है।",
  },

  /* ----------------------------------------------------------- leaderboard */
  "board.title": { en: "Leaderboard", hi: "लीडरबोर्ड" },
  "board.sub": {
    en: "Best seasons by anyone, anywhere. Tap a row to replay the exact run.",
    hi: "कहीं के भी, किसी के भी सबसे अच्छे सीज़न। किसी लाइन पर टैप करके वही रन दोबारा देखिए।",
  },
  "board.tab.daily": { en: "Today's challenge", hi: "आज की चुनौती" },
  "board.tab.allTime": { en: "All time", hi: "ऑल टाइम" },
  "board.loading": { en: "Loading the board…", hi: "बोर्ड आ रहा है…" },
  "board.empty.daily": { en: "No runs logged yet today. Be the first.", hi: "आज अभी तक कोई रन दर्ज नहीं। पहले आप होइए।" },
  "board.empty.allTime": { en: "No seasons logged yet.", hi: "अभी तक कोई सीज़न दर्ज नहीं।" },
  "board.todayNote": {
    en: "Today is {date}. The board resets at midnight IST.",
    hi: "आज {date} है। बोर्ड आधी रात (IST) पर रीसेट होता है।",
  },
  "board.seedNote": { en: "Every run is verifiable from its seed.", hi: "हर रन उसकी सीड से जाँचा जा सकता है।" },
  "board.manager": { en: "Manager {id}", hi: "मैनेजर {id}" },
  "board.perfect": { en: "PERFECT", hi: "परफ़ेक्ट" },
  "board.rowMeta": {
    en: "{difficulty} · {outcome} · net run rate {nrr}",
    hi: "{difficulty} · {outcome} · नेट रन रेट {nrr}",
  },
  "outcome.champions": { en: "champions", hi: "चैंपियन" },
  "outcome.madePlayoffs": { en: "made the playoffs", hi: "प्लेऑफ़ तक पहुँचे" },
  "outcome.missedPlayoffs": { en: "missed the playoffs", hi: "प्लेऑफ़ से चूके" },

  /* ---------------------------------------------------------- shared words */
  "word.won": { en: "Won", hi: "जीते" },
  "word.lost": { en: "Lost", hi: "हारे" },
  "word.points": { en: "points", hi: "अंक" },
  "word.nrr": { en: "net run rate", hi: "नेट रन रेट" },
  "word.difficulty": { en: "difficulty", hi: "कठिनाई" },
  "word.onTheTable": { en: "on the table", hi: "अंक तालिका में" },
  "word.runsScored": { en: "runs scored", hi: "बनाए रन" },
  "difficulty.Rookie": { en: "Rookie", hi: "रूकी" },
  "difficulty.Pro": { en: "Pro", hi: "प्रो" },
  "difficulty.Legend": { en: "Legend", hi: "लेजेंड" },
  "role.Opener": { en: "Opener", hi: "ओपनर" },
  "role.Middle": { en: "Middle", hi: "मिडल ऑर्डर" },
  "role.WK": { en: "Keeper", hi: "विकेटकीपर" },
  "role.AR": { en: "All-rounder", hi: "ऑलराउंडर" },
  "role.Pace": { en: "Pace", hi: "तेज़ गेंदबाज़" },
  "role.Spin": { en: "Spin", hi: "स्पिन" },
  /* -------------------------------------------------------------- run bar */
  "draft.respinsLeft": { en: "{n} re-spins left", hi: "{n} री-स्पिन बचे" },
  "run.restart": { en: "Restart run", hi: "रन दोबारा शुरू करें" },
  "run.soundOn": { en: "Sound on", hi: "आवाज़ चालू" },
  "run.soundOff": { en: "Sound off", hi: "आवाज़ बंद" },
  "run.classic": { en: "Classic", hi: "क्लासिक" },
  "run.dailyWithDate": { en: "Today's challenge · {date}", hi: "आज की चुनौती · {date}" },
  "run.room": { en: "Room {code}", hi: "रूम {code}" },

  /* ---------------------------------------------------------------- setup */
  "setup.title": { en: "Set up your run", hi: "अपना रन सेट कीजिए" },
  "setup.sub": { en: "Three choices, then the board starts spinning.", hi: "तीन चुनाव, फिर बोर्ड घूमना शुरू।" },
  "setup.mode": { en: "Mode", hi: "मोड" },
  "setup.classicSub": { en: "Fresh spins every run", hi: "हर रन में नई स्पिन" },
  "setup.dailySub": { en: "Same 11 squads for all", hi: "सबके लिए वही 11 स्क्वाड" },
  "setup.shape": { en: "Shape of your XI", hi: "आपकी XI का ढाँचा" },
  "setup.always11": { en: "Always 11 players", hi: "हमेशा 11 खिलाड़ी" },
  "setup.difficulty": { en: "Difficulty", hi: "कठिनाई" },
  "setup.rookieSub": { en: "Weaker teams", hi: "कमज़ोर टीमें" },
  "setup.proSub": { en: "True sim", hi: "असली सिम" },
  "setup.legendSub": { en: "Ratings hidden", hi: "रेटिंग छिपी" },
  "setup.start": { en: "Start the draft", hi: "ड्राफ़्ट शुरू करें" },
  "setup.rules": { en: "11 spins · 2 re-spins · max 4 overseas players", hi: "11 स्पिन · 2 री-स्पिन · ज़्यादा से ज़्यादा 4 विदेशी" },
  "setup.roomLocked": { en: "Room rules are locked:", hi: "रूम के नियम तय हैं:" },
  "setup.friendBlurb": { en: "You both draft your own XI, then one 18-game league decides it.", hi: "दोनों अपनी XI चुनते हैं, फिर 18 मैच की एक लीग फ़ैसला करती है।" },
  "setup.yourName": { en: "Your name", hi: "आपका नाम" },
  "setup.createRoom": { en: "Create a room", hi: "रूम बनाएँ" },
  "setup.inviteTitle": { en: "Shared league invite", hi: "साझा लीग का न्योता" },
  "setup.inviteRules": { en: "{difficulty} · your own spins, your own style, one 18-game table", hi: "{difficulty} · अपनी स्पिन, अपना अंदाज़, एक ही 18-मैच की तालिका" },
  "setup.join": { en: "Join", hi: "जुड़ें" },
  "setup.joining": { en: "Joining…", hi: "जुड़ रहे हैं…" },
  "setup.playingAs": { en: "Playing as", hi: "आप खेल रहे हैं" },
  "setup.draftBelow": { en: "Draft your own XI below, then lock it in.", hi: "नीचे अपनी XI चुनिए, फिर लॉक कर दीजिए।" },
  "setup.findingRoom": { en: "Finding room {code}…", hi: "रूम {code} खोजा जा रहा है…" },
  "setup.noRoom": { en: "No room with that code. It may have expired.", hi: "इस कोड का कोई रूम नहीं। शायद खत्म हो गया।" },
  "setup.normalRun": { en: "Start a normal run", hi: "सामान्य रन शुरू करें" },
  "style.Balanced": { en: "Balanced", hi: "संतुलित" },
  "style.Pace Attack": { en: "Pace Attack", hi: "तेज़ गेंदबाज़ी" },
  "style.Spin Twins": { en: "Spin Twins", hi: "दो स्पिनर" },
  "style.Batting Heavy": { en: "Batting Heavy", hi: "बल्लेबाज़ी भारी" },
  "style.blurb.Balanced": { en: "The classic", hi: "क्लासिक" },
  "style.blurb.Pace Attack": { en: "Three quicks, one spinner", hi: "तीन तेज़, एक स्पिनर" },
  "style.blurb.Spin Twins": { en: "Two spinners strangle", hi: "दो स्पिनर, दम घोंटो" },
  "style.blurb.Batting Heavy": { en: "Four middle-order guns", hi: "चार मिडल ऑर्डर बल्लेबाज़" },

  /* ---------------------------------------------------------------- draft */
  "draft.pickOf": { en: "Pick {n} of 11", hi: "11 में से {n}वाँ चुनाव" },
  "draft.slotsOpen": { en: "{n} slots still open", hi: "{n} जगह अब भी खाली" },
  "draft.squad": { en: "Squad", hi: "स्क्वाड" },
  "draft.season": { en: "Season", hi: "सीज़न" },
  "draft.spinBoard": { en: "Spin the board", hi: "बोर्ड घुमाएँ" },
  "draft.spinning": { en: "Spinning…", hi: "घूम रहा है…" },
  "draft.spinHint": { en: "156 real team-seasons, 2008 to 2025. Tap the board or press space.", hi: "2008 से 2025 तक की 156 असली टीम-सीज़न। बोर्ड पर टैप कीजिए या स्पेस दबाइए।" },
  "draft.respin": { en: "Re-spin · {n} left", hi: "री-स्पिन · {n} बचे" },
  "draft.teamSeason": { en: "{name}, {season}", hi: "{name}, {season}" },
  "draft.takeOne": { en: "Take one player from this squad.", hi: "इस स्क्वाड से एक खिलाड़ी चुनिए।" },
  "draft.legendNote": { en: "Legend mode. Ratings are hidden, trust what you know.", hi: "लेजेंड मोड। रेटिंग छिपी है, अपनी जानकारी पर भरोसा कीजिए।" },
  "draft.pickFrom": { en: "Pick one from the {season} squad", hi: "{season} की स्क्वाड से एक चुनिए" },
  "draft.stillOpen": { en: "Still open: {roles}", hi: "अब भी खाली: {roles}" },
  "draft.deadSpin": { en: "Dead spin — anyone goes", hi: "डेड स्पिन — कोई भी चलेगा" },
  "draft.noFit": { en: "No one from this squad fits", hi: "इस स्क्वाड से कोई फ़िट नहीं बैठता" },
  "draft.standIns": { en: "Stand-ins who fit your open slots:", hi: "आपकी खाली जगहों में फ़िट बैठने वाले विकल्प:" },
  "draft.xiSoFar": { en: "Your XI so far", hi: "अब तक आपकी XI" },
  "draft.overseasCount": { en: "{n} of 4 overseas", hi: "4 में से {n} विदेशी" },
  "draft.notPicked": { en: "Not picked yet", hi: "अभी नहीं चुना" },
  "draft.overQuota": { en: "Over quota: {names}", hi: "कोटा से ज़्यादा: {names}" },
  "draft.capFull": { en: "Overseas cap full, 4 of 4", hi: "विदेशी कोटा पूरा, 4 में से 4" },
  "draft.slotFilled": { en: "{role} slot filled", hi: "{role} की जगह भर चुकी" },
  "draft.alreadyPicked": { en: "Already in your XI", hi: "पहले से आपकी XI में" },

  /* ------------------------------------------------------------- XI locked */
  "xi.locked": { en: "Your XI is locked", hi: "आपकी XI लॉक हो गई" },
  "xi.lockedSub": { en: "Eleven picks done. Check the forecast, then play.", hi: "ग्यारह चुनाव पूरे। अनुमान देखिए, फिर खेलिए।" },
  "xi.lockedRoomSub": { en: "Lock it in for the room. The shared league plays from both XIs.", hi: "रूम के लिए लॉक कीजिए। साझा लीग दोनों XI से खेली जाएगी।" },
  "xi.penalty": { en: "{errors}. The sim runs anyway, with a penalty.", hi: "{errors}। सिम फिर भी चलेगा, पर पेनल्टी के साथ।" },
  "xi.teamPower": { en: "Team power", hi: "टीम पावर" },
  "xi.batting": { en: "Batting", hi: "बल्लेबाज़ी" },
  "xi.bowling": { en: "Bowling", hi: "गेंदबाज़ी" },
  "xi.overseas": { en: "Overseas", hi: "विदेशी" },
  "xi.hidden": { en: "Hidden", hi: "छिपी" },
  "xi.ofFour": { en: "{n} of 4", hi: "4 में से {n}" },
  "xi.bookies": { en: "Bookies say", hi: "सटोरियों का कहना" },
  "xi.expPoints": { en: "points", hi: "अंक" },
  "xi.likelyFinish": { en: "likely finish", hi: "संभावित स्थान" },
  "xi.makePlayoffs": { en: "make playoffs", hi: "प्लेऑफ़ में जगह" },
  "xi.winTitle": { en: "win the title", hi: "ख़िताब जीतना" },
  "xi.playSeason": { en: "Play the season", hi: "सीज़न खेलिए" },
  "xi.playNote": { en: "14 league games, then the playoffs. Top 4 go through.", hi: "14 लीग मैच, फिर प्लेऑफ़। ऊपर की 4 टीमें आगे।" },
  "xi.theXI": { en: "The XI", hi: "आपकी XI" },
  "xi.lockIn": { en: "Lock in this XI", hi: "यह XI लॉक कीजिए" },
  "xi.locking": { en: "Locking…", hi: "लॉक हो रहा है…" },
  "xi.startLeague": { en: "Start the league", hi: "लीग शुरू करें" },
  "xi.waitingOpponent": { en: "XI locked — waiting for your opponent", hi: "XI लॉक — विपक्षी का इंतज़ार" },
  "unit.Elite": { en: "Elite", hi: "बेहतरीन" },
  "unit.Strong": { en: "Strong", hi: "मज़बूत" },
  "unit.Solid": { en: "Solid", hi: "ठीक-ठाक" },
  "unit.Modest": { en: "Modest", hi: "कमज़ोर" },
  "unit.Shaky": { en: "Shaky", hi: "लचर" },

  /* --------------------------------------------------------------- league */
  "league.matchOf": { en: "Match {n} of 14", hi: "14 में से {n}वाँ मैच" },
  "league.complete": { en: "League complete", hi: "लीग पूरी" },
  "league.unbeaten": { en: "Still unbeaten. {n} more to go.", hi: "अब तक अजेय। {n} और बाकी।" },
  "league.oneDefeat": { en: "One defeat. The perfect season is gone.", hi: "एक हार। परफ़ेक्ट सीज़न हाथ से गया।" },
  "league.record": { en: "{w} won, {l} lost.", hi: "{w} जीते, {l} हारे।" },
  "league.finishedLine": { en: "Finished {rank} on {points} points. {note}", hi: "{rank} स्थान पर, {points} अंक। {note}" },
  "league.inTopFour": { en: "Into the top four.", hi: "ऊपर की चार में।" },
  "league.outsideTopFour": { en: "Outside the top four.", hi: "ऊपर की चार से बाहर।" },
  "league.results": { en: "Results so far", hi: "अब तक के नतीजे" },
  "league.tapAhead": { en: "Tap a result to jump ahead", hi: "आगे बढ़ने के लिए किसी नतीजे पर टैप कीजिए" },
  "league.speed": { en: "Speed {n}x", hi: "रफ़्तार {n}x" },
  "league.skip": { en: "Skip to end", hi: "अंत तक जाएँ" },
  "league.threeWins": { en: "Three wins from the title.", hi: "ख़िताब से तीन जीत दूर।" },
  "league.intoPlayoffs": { en: "Into the playoffs", hi: "प्लेऑफ़ में" },
  "table.title": { en: "The table", hi: "अंक तालिका" },
  "table.topFour": { en: "Top 4 go through", hi: "ऊपर की 4 आगे" },
  "table.team": { en: "Team", hi: "टीम" },
  "table.yourXI": { en: "Your XI", hi: "आपकी XI" },
  "table.cut": { en: "Playoff cut", hi: "प्लेऑफ़ की रेखा" },

  /* -------------------------------------------------------------- results */
  "match.won": { en: "Won by {margin}", hi: "{margin} से जीते" },
  "match.lost": { en: "Lost by {margin}", hi: "{margin} से हारे" },
  "match.wonSO": { en: "Won in a super over", hi: "सुपर ओवर में जीते" },
  "match.lostSO": { en: "Lost in a super over", hi: "सुपर ओवर में हारे" },
  "match.beat": { en: "Beat {opp} by {margin}", hi: "{opp} को {margin} से हराया" },
  "match.lostTo": { en: "Lost to {opp} by {margin}", hi: "{opp} से {margin} से हारे" },
  "match.beatSO": { en: "Beat {opp} in a super over", hi: "{opp} को सुपर ओवर में हराया" },
  "match.lostToSO": { en: "Lost to {opp} in a super over", hi: "{opp} से सुपर ओवर में हारे" },
  "unit.runs": { en: "runs", hi: "रन" },
  "unit.run": { en: "run", hi: "रन" },
  "unit.wickets": { en: "wickets", hi: "विकेट" },
  "unit.wicket": { en: "wicket", hi: "विकेट" },
  "unit.ballsLeft": { en: "balls left", hi: "गेंद बाकी" },
  "hero.defended": { en: "{name} {w} for {r} defended it", hi: "{name} ने {w}/{r} लेकर बचा लिया" },
  "hero.finished": { en: "{name} {runs} off {balls} finished it", hi: "{name} ने {balls} गेंद में {runs} बनाकर जिता दिया" },
  "hero.opp": { en: "{name} stunned you", hi: "{name} ने चौंका दिया" },

  /* ------------------------------------------------------------- knockouts */
  "po.title": { en: "Playoffs", hi: "प्लेऑफ़" },
  "po.via": { en: "in as #{rank} on {w}-{l}", hi: "{w}-{l} के साथ #{rank} पर" },
  "po.theFinal": { en: "The final", hi: "फ़ाइनल" },
  "po.versus": { en: "You versus {opp}", hi: "आप बनाम {opp}" },
  "po.oneGame": { en: "One game, played ball by ball.", hi: "एक मैच, गेंद-दर-गेंद।" },
  "po.playFinal": { en: "Play the final", hi: "फ़ाइनल खेलिए" },
  "po.next": { en: "Next: {stage}", hi: "आगे: {stage}" },
  "po.toFinal": { en: "To the final", hi: "फ़ाइनल तक" },
  "po.seasonOver": { en: "Season over — see the results", hi: "सीज़न ख़त्म — नतीजे देखिए" },
  "po.liftTrophy": { en: "Lift the trophy", hi: "ट्रॉफ़ी उठाइए" },
  "po.fullTime": { en: "Full time — see the results", hi: "मैच ख़त्म — नतीजे देखिए" },
  "stage.Final": { en: "the final", hi: "फ़ाइनल" },
  "stage.Qualifier 1": { en: "Qualifier 1", hi: "क्वालिफ़ायर 1" },
  "stage.Qualifier 2": { en: "Qualifier 2", hi: "क्वालिफ़ायर 2" },
  "stage.Eliminator": { en: "Eliminator", hi: "एलिमिनेटर" },
  "stage.Eliminator / Q2": { en: "Eliminator / Q2", hi: "एलिमिनेटर / क्वा. 2" },
  "stage.playoffs": { en: "the playoffs", hi: "प्लेऑफ़" },

  /* ---------------------------------------------------------- end of season */
  "end.perfect": { en: "Champions. Perfect season.", hi: "चैंपियन। परफ़ेक्ट सीज़न।" },
  "end.champions": { en: "Champions.", hi: "चैंपियन।" },
  "end.knockedOut": { en: "Knocked out in {stage}.", hi: "{stage} में बाहर।" },
  "end.missed": { en: "Missed the playoffs.", hi: "प्लेऑफ़ से चूक गए।" },
  "end.recordLine": { en: "{w} won, {l} lost, {points} points, finished {rank}.", hi: "{w} जीते, {l} हारे, {points} अंक, {rank} स्थान।" },
  "end.capsLine": { en: "{orange} led the runs with {runs} and {purple} took {wickets} wickets.", hi: "{orange} ने {runs} रन बनाए और {purple} ने {wickets} विकेट लिए।" },
  "end.neverDone": { en: "Nobody had done this before.", hi: "ऐसा पहले कभी नहीं हुआ।" },
  "end.promisedLand": { en: "Top four was the promised land.", hi: "ऊपर की चार में जगह ही मंज़िल थी।" },
  "end.playAnother": { en: "Play another run", hi: "एक और रन खेलिए" },
  "end.playAnotherNote": { en: "Your next run gets a fresh board. Today's challenge stays the same for everyone until midnight.", hi: "अगले रन में नया बोर्ड मिलेगा। आज की चुनौती आधी रात तक सबके लिए वही रहेगी।" },

  /* ---------------------------------------------------------------- share */
  "share.whatsapp": { en: "Share on WhatsApp", hi: "WhatsApp पर भेजें" },
  "share.copy": { en: "Copy result card", hi: "नतीजा कॉपी करें" },
  "share.copied": { en: "Copied", hi: "कॉपी हो गया" },
  "share.challenge": { en: "Challenge a friend", hi: "दोस्त को चुनौती दें" },
  "share.linkCopied": { en: "Link copied", hi: "लिंक कॉपी हो गया" },
  "share.replayNote": { en: "Anyone can replay this exact run at /r/{seed}", hi: "कोई भी यही रन /r/{seed} पर दोबारा देख सकता है" },
  "share.beatMyBoard": { en: "Beat my board: {url}", hi: "मेरा बोर्ड हराकर दिखाओ: {url}" },

  "report.xiNumbers": { en: "Your XI, season numbers", hi: "आपकी XI, सीज़न के आँकड़े" },
  "report.matches": { en: "{n} matches", hi: "{n} मैच" },
  "report.player": { en: "Player", hi: "खिलाड़ी" },
  "report.role": { en: "Role", hi: "भूमिका" },
  "report.runs": { en: "Runs", hi: "रन" },
  "report.wickets": { en: "Wickets", hi: "विकेट" },
  "report.rating": { en: "Rating", hi: "रेटिंग" },
  "report.awards": { en: "Season awards", hi: "सीज़न के पुरस्कार" },
  "report.orangeCap": { en: "Orange Cap, most runs", hi: "ऑरेंज कैप, सबसे ज़्यादा रन" },
  "report.purpleCap": { en: "Purple Cap, most wickets", hi: "पर्पल कैप, सबसे ज़्यादा विकेट" },
  "report.mvp": { en: "Player of the season", hi: "सीज़न के सर्वश्रेष्ठ खिलाड़ी" },
  "report.finished": { en: "finished", hi: "स्थान" },
  "report.bookiesSaid": { en: "the bookies said", hi: "सटोरियों का अनुमान" },
  "report.batting": { en: "batting", hi: "बल्लेबाज़ी" },
  "report.bowling": { en: "bowling", hi: "गेंदबाज़ी" },
  "report.theBatting": { en: "the batting", hi: "बल्लेबाज़ी" },
  "report.theBowling": { en: "the bowling", hi: "गेंदबाज़ी" },
  "report.recordLine": { en: "{w} won, {l} lost, {points} points, finished #{rank}.", hi: "{w} जीते, {l} हारे, {points} अंक, {rank}वाँ स्थान।" },
  "report.noWeak": { en: "No weak links. This XI had everything.", hi: "कोई कमज़ोर कड़ी नहीं। इस XI में सब कुछ था।" },
  "report.weakLink": { en: "This XI was built on {strength} {unit}, and {weak} let it down.", hi: "यह XI {strength} {unit} पर टिकी थी, और {weak} ने निराश किया।" },
  "verdict.perfect14": { en: "Fourteen from fourteen in the league.", hi: "लीग में चौदह में से चौदह।" },
  "verdict.top": { en: "Top of the table.", hi: "अंक तालिका में सबसे ऊपर।" },
  "verdict.through": { en: "Through to the knockouts.", hi: "नॉकआउट में जगह पक्की।" },
  "verdict.rightThere": { en: "The playoffs were right there.", hi: "प्लेऑफ़ बिलकुल सामने था।" },
  "verdict.midTable": { en: "Mid-table, and nowhere near it.", hi: "बीच की तालिका, दौड़ से कोसों दूर।" },
  "verdict.bottom": { en: "Rock bottom.", hi: "सबसे नीचे।" },
  "pm.complete": { en: "Complete", hi: "पूरा" },
  "pm.superOver": { en: "Super over", hi: "सुपर ओवर" },
  "pm.batting1st": { en: "{side} batting · 1st innings", hi: "{side} बल्लेबाज़ी · पहली पारी" },
  "pm.batting2nd": { en: "{side} batting · 2nd innings", hi: "{side} बल्लेबाज़ी · दूसरी पारी" },
  "pm.battedFirst": { en: "{overs} overs, batted first", hi: "{overs} ओवर, पहले बल्लेबाज़ी" },
  "pm.chasingOvers": { en: "{overs} overs, chasing {target}", hi: "{overs} ओवर, {target} का पीछा" },
  "pm.chasing": { en: "chasing {target}", hi: "{target} का पीछा" },
  "pm.neededOff": { en: "needed off {n} balls", hi: "चाहिए, {n} गेंद में" },
  "pm.neededOffOne": { en: "needed off 1 ball", hi: "चाहिए, 1 गेंद में" },
  "pm.chasedDown": { en: "Chased down.", hi: "लक्ष्य हासिल।" },
  "pm.bowlerTo": { en: "{bowler} to {striker}", hi: "{bowler} की गेंद, {striker} पर" },
  "pm.over": { en: "Over {n}", hi: "ओवर {n}" },
  "pm.finalOver": { en: "Final over, and it is still alive.", hi: "आख़िरी ओवर, और मुक़ाबला अब भी ज़िंदा।" },
  "pm.working": { en: "Working through the overs.", hi: "ओवर निकल रहे हैं।" },
  "pm.cruising": { en: "Cruising. Fast-forwarding.", hi: "आराम से। तेज़ी से आगे।" },
  "pm.afterOvers": { en: "after {overs} overs", hi: "{overs} ओवर के बाद" },
  "pm.won": { en: "WON", hi: "जीते" },
  "pm.lost": { en: "LOST", hi: "हारे" },
  "pm.byRuns": { en: "by {n} runs", hi: "{n} रन से" },
  "pm.byWickets": { en: "by {w} wickets, {b} balls left", hi: "{w} विकेट से, {b} गेंद बाकी" },
  "pm.byWicketsShort": { en: "by {w} wickets", hi: "{w} विकेट से" },
  "pm.inSuperOver": { en: "in a super over, {line}", hi: "सुपर ओवर में, {line}" },
  "pm.versusLine": { en: "{you} {a} versus {b} {opp}", hi: "{you} {a} बनाम {b} {opp}" },
  "pm.soSide": { en: "Super over · {side}", hi: "सुपर ओवर · {side}" },
  "pm.soOther": { en: "{side} made {score}, needs {n}", hi: "{side} ने {score} बनाए, चाहिए {n}" },
  "pm.soComplete": { en: "Super over complete", hi: "सुपर ओवर पूरा" },
  "pm.soLastThree": { en: "Last three balls", hi: "आख़िरी तीन गेंदें" },
  "pm.innings1": { en: "{side}, 1st innings", hi: "{side}, पहली पारी" },
  "pm.innings2": { en: "{side}, 2nd innings", hi: "{side}, दूसरी पारी" },
  "pm.batter": { en: "Batter", hi: "बल्लेबाज़" },
  "pm.balls": { en: "Balls", hi: "गेंद" },
  "pm.notOut": { en: "not out", hi: "नाबाद" },
  "pm.bowler": { en: "Bowler", hi: "गेंदबाज़" },
  "pm.overs": { en: "Overs", hi: "ओवर" },
  "pm.wkts": { en: "Wkts", hi: "विकेट" },
  "pm.show": { en: "Show", hi: "दिखाएँ" },
  "pm.hide": { en: "Hide", hi: "छिपाएँ" },
  "pm.close": { en: "Close", hi: "बंद करें" },
  "room.computing": { en: "Working out the shared season…", hi: "साझा सीज़न तैयार हो रहा है…" },
  "room.youAre": { en: "You are {name}", hi: "आप हैं {name}" },
  "room.roundOf": { en: "Round {n} of 18", hi: "18 में से {n}वाँ राउंड" },
  "room.unbeatenAfter": { en: "Still unbeaten after {n}.", hi: "{n} मैच बाद भी अजेय।" },
  "room.yourResults": { en: "Your results", hi: "आपके नतीजे" },
  "room.scoreKeyYours": { en: "your score", hi: "आपका स्कोर" },
  "room.scoreKeyTheirs": { en: "theirs", hi: "उनका" },
  "room.headToHead": { en: "Head to head with {name}", hi: "{name} से आमना-सामना" },
  "room.h2hRound": { en: "Head to head, round {n}", hi: "आमना-सामना, राउंड {n}" },
  "room.theirNight": { en: "their night", hi: "उनका दिन था" },
  "room.wonSO": { en: "Won a super over, {note}", hi: "सुपर ओवर जीता, {note}" },
  "room.lostSO": { en: "Lost a super over, {note}", hi: "सुपर ओवर हारा, {note}" },
  "room.feedLine": { en: "{result} · {hero}", hi: "{result} · {hero}" },
  "room.heroBowl": { en: "{name} {w} for {r}", hi: "{name} {w}/{r}" },
  "room.heroBat": { en: "{name} {runs} off {balls}", hi: "{name} {runs} ({balls})" },
  "room.seasonEnds": { en: "Outside the top four. Your season ends here.", hi: "ऊपर की चार से बाहर। आपका सीज़न यहीं ख़त्म।" },
  "room.seeFinish": { en: "See how the room finished", hi: "देखिए रूम में क्या हुआ" },
  "room.resultPending": { en: "Result pending…", hi: "नतीजा बाकी…" },
  "room.finalVersus": { en: "{me} versus {opp}", hi: "{me} बनाम {opp}" },
  "room.downToQ2": { en: "Down to Qualifier 2", hi: "क्वालिफ़ायर 2 में" },
  "room.noSpoilers": { en: "No spoilers.", hi: "कोई स्पॉइलर नहीं।" },
  "room.stillWatching": { en: "{name} is still watching their season. Your result is ready and appears here the moment they finish. This page updates on its own.", hi: "{name} अभी अपना सीज़न देख रहे हैं। आपका नतीजा तैयार है और उनके ख़त्म करते ही यहाँ दिख जाएगा। यह पेज अपने आप अपडेट होता है।" },
  "room.yourSeason": { en: "Your season: {w}-{l}, {status}.", hi: "आपका सीज़न: {w}-{l}, {status}।" },
  "room.knockedOutIn": { en: "knocked out in {stage}", hi: "{stage} में बाहर" },
  "room.noPlayoffsShort": { en: "no playoffs", hi: "प्लेऑफ़ नहीं" },
  "room.finishedOn": { en: "Finished {rank} on {points} points.", hi: "{rank} स्थान, {points} अंक।" },
  "room.winsRoom": { en: "{name} wins the room.", hi: "{name} ने रूम जीता।" },
  "room.noPlayoffsLine": { en: "{w}-{l}, no playoffs.", hi: "{w}-{l}, प्लेऑफ़ नहीं।" },
  "room.youFinished": { en: "You finished {rank} on {points} points, net run rate {nrr}{tail}", hi: "आप {rank} स्थान पर रहे, {points} अंक, नेट रन रेट {nrr}{tail}" },
  "room.outIn": { en: ", out in {stage}.", hi: ", {stage} में बाहर।" },
  "room.sharedTable": { en: "The shared table", hi: "साझा अंक तालिका" },
  "room.you": { en: "(you)", hi: "(आप)" },
  "room.copyResult": { en: "Copy the result", hi: "नतीजा कॉपी करें" },
  "room.livesAt": { en: "This room lives at /m/{code}", hi: "यह रूम /m/{code} पर है" },
  "room.shareText": { en: "{name} went {w}-{l} in a shared 18-game room season{won} — {url}", hi: "{name} ने साझा 18-मैच रूम सीज़न में {w}-{l} किया{won} — {url}" },
  "room.andWonIt": { en: " and WON IT", hi: " और जीत भी लिया" },
  "seed.checking": { en: "Checking the seed…", hi: "सीड जाँची जा रही है…" },
  "seed.notFound": { en: "No season saved for this seed", hi: "इस सीड का कोई सीज़न सेव नहीं" },
  "seed.notFoundBody": { en: "This link may be a fresh board rather than a finished run. Play it yourself and the result saves under the same seed.", hi: "यह लिंक शायद पूरे रन के बजाय एक नया बोर्ड है। खुद खेलिए, नतीजा इसी सीड पर सेव हो जाएगा।" },
  "seed.playRun": { en: "Play a run", hi: "एक रन खेलिए" },
  "seed.madePlayoffs": { en: "Made the playoffs.", hi: "प्लेऑफ़ तक पहुँचे।" },
  "seed.note": { en: "Seed {seed}. The same seed and the same board reproduce this season exactly.", hi: "सीड {seed}। वही सीड और वही बोर्ड यह सीज़न हूबहू दोहरा देंगे।" },
  "seed.theLeague": { en: "The league", hi: "लीग" },
  "seed.playYourOwn": { en: "Play your own run", hi: "अपना रन खेलिए" },
  "seed.savedAt": { en: "Saved {when}", hi: "{when} को सेव" },

  "mroom.finding": { en: "Finding the room…", hi: "रूम खोजा जा रहा है…" },
  "mroom.noRoomTitle": { en: "No room with that code", hi: "इस कोड का कोई रूम नहीं" },
  "mroom.noRoomBody": { en: "Codes look like KX7Q2M. Check the link, or start a new room from the home page.", hi: "कोड ऐसे दिखते हैं: KX7Q2M। लिंक जाँचिए, या होम पेज से नया रूम बनाइए।" },
  "mroom.roomCode": { en: "Room code", hi: "रूम कोड" },
  "mroom.bothSeats": { en: "both seats taken", hi: "दोनों सीटें भरीं" },
  "mroom.oneSeat": { en: "one seat open", hi: "एक सीट खाली" },
  "mroom.openSeat": { en: "Open seat", hi: "खाली सीट" },
  "mroom.waitingFriend": { en: "Waiting for a friend", hi: "दोस्त का इंतज़ार" },
  "mroom.xiLocked": { en: "XI locked", hi: "XI लॉक" },
  "mroom.drafting": { en: "Drafting", hi: "चुन रहे हैं" },
  "mroom.sendInvite": { en: "Send invite on WhatsApp", hi: "WhatsApp पर न्योता भेजें" },
  "mroom.orCopy": { en: "Or copy the link: {url}", hi: "या लिंक कॉपी कीजिए: {url}" },
  "mroom.takeSeat": { en: "Take the open seat", hi: "खाली सीट लीजिए" },
  "mroom.full": { en: "This room is full. Rematches are free — ask the host to start a new one.", hi: "यह रूम भरा है। दोबारा खेलना मुफ़्त है — होस्ट से नया रूम बनवाइए।" },
  "mroom.draftAgainst": { en: "Draft against {name}", hi: "{name} के ख़िलाफ़ चुनिए" },
  "mroom.startDraft": { en: "Start your draft", hi: "अपना ड्राफ़्ट शुरू करें" },
  "mroom.waitingFor": { en: "Your XI is locked. Waiting for {name} to finish drafting. This page updates on its own.", hi: "आपकी XI लॉक है। {name} के चुनाव पूरा करने का इंतज़ार। यह पेज अपने आप अपडेट होता है।" },
  "mroom.opponent": { en: "your opponent", hi: "आपके विपक्षी" },
  "mroom.howTitle": { en: "How a 1v1 works", hi: "1v1 कैसे चलता है" },
  "mroom.how1": { en: "Each of you spins your own board and drafts your own XI. Same difficulty, same rules.", hi: "दोनों अपना-अपना बोर्ड घुमाते हैं और अपनी XI चुनते हैं। कठिनाई वही, नियम वही।" },
  "mroom.how2": { en: "Once both XIs are locked, one 18-game league plays out with both teams in it. You meet each other twice.", hi: "दोनों XI लॉक होते ही 18 मैच की एक लीग चलती है जिसमें दोनों टीमें होती हैं। आप दो बार आमने-सामने आते हैं।" },
  "mroom.how3": { en: "Whoever finishes higher wins the room. A playoff final between you settles a tie.", hi: "जो ऊपर रहेगा वही रूम जीतेगा। बराबरी होने पर आपस का फ़ाइनल फ़ैसला करेगा।" },
  "mroom.headerMeta": { en: "Room {code} · {difficulty} · one 18-game table", hi: "रूम {code} · {difficulty} · एक 18-मैच की तालिका" },
  "mroom.inviteText": { en: "Play me at 14-0, the IPL draft game. Room {code}: {url}", hi: "मुझसे 14-0 खेलो, IPL ड्राफ़्ट गेम। रूम {code}: {url}" },
  "mroom.against": { en: " against ", hi: " बनाम " },
  /* ------------------------------------------------------------- ordinals */
  "ord.1": { en: "1st", hi: "पहले" },
  "ord.2": { en: "2nd", hi: "दूसरे" },
  "ord.3": { en: "3rd", hi: "तीसरे" },
  "ord.4": { en: "4th", hi: "चौथे" },
  "ord.5": { en: "5th", hi: "पाँचवें" },
  "ord.6": { en: "6th", hi: "छठे" },
  "ord.7": { en: "7th", hi: "सातवें" },
  "ord.8": { en: "8th", hi: "आठवें" },
  "ord.9": { en: "9th", hi: "नौवें" },
  "ord.10": { en: "10th", hi: "दसवें" },
};
